### ISSUE TITLE
south database module not supported with python 1.7 or later

### ISSUE THREAD

**Issue by kkiran33** [Proper-Job/django-mobile-app-distribution#1]
There is no South database module 'south.db.sqlite3' for your database. Please either choose a supported database, check for SOUTH_DATABASE_ADAPTER[S] settings, or remove South from INSTALLED_APPS.

**Comment by Proper-Job** [comment]
Hi
Could you elaborate a bit more?

**Comment by Proper-Job** [comment]
I'll upload a fix to pypi as soon as I can.

**Comment by Proper-Job** [comment]
I'll upload a fix as soon as pypi is accepting packages again: https://bitbucket.org/pypa/pypi/issue/262/getting-500-error-when-uploading-python

**Comment by Proper-Job** [comment]
Fixed in 0.3.1
