### ISSUE TITLE
Manage.py missing

### ISSUE THREAD

**Issue by ianwhite2** [Proper-Job/django-mobile-app-distribution#5]
Hi Moritz ,

I am a newbie to python and Django , in ur instruction it is said to run python manage.py migrate
but there is no manage.py .

Can you please help me on this

**Comment by Proper-Job** [comment]
@ianwhite2 manage.py is created on every django installation.  Please refer to the [official documentation](https://docs.djangoproject.com/en/1.10/ref/django-admin/).

**Comment by ianwhite2** [comment]
Got it working sorry for the rookie question  but now I created a superuser and when I login it just give me a blank page.
Any guidance u can give
